### ISSUE TITLE
Unable to paste in CC number

### ISSUE THREAD

**Issue by booch** [abadi199/elm-creditcard#13]
I tried out the live demo, and it looks really nice. However, I noticed that I wasn't able to paste a credit-card number in the box using the keyboard (Command+V on a Mac). For those of us using password managers, this is a pretty big deal.

I did find that I could paste using the context menu, so I assume there's some event handler catching keyboard entry, probably to restrict entry to numeric digits.

**Comment by abadi199** [comment]
I've handled copy paste on Linux and Windows, by detecting modifier key press, but not the command key on Mac. I think I've fix this with this commit https://github.com/abadi199/elm-creditcard/commit/dbd27bd130148b64560f231eb40563513b7a947c, but I don't have a Mac keyboard to test this out. Do you mind trying out on the live demo and see if it's working now?

**Comment by booch** [comment]
Yup, that works. Thanks!
