### ISSUE TITLE
Bug: Can't use a zeroes inside inputs

### ISSUE THREAD

**Issue by pablo-co** [abadi199/elm-creditcard#17]
In the current card form you can't have leading zeroes on the expiration month nor CVC (they get removed). This makes it a little frustrating for people trying to write a single digit month using the prefix zero (ex. 01, 02) and impossible to input some CVCs (ex. 043, 008, 097).

**Comment by abadi199** [comment]
Thanks for reporting this bug. It's fixed here 2aa5d523e9e33a15e3e096c045d8e466aee65c42 and published to elm package as `v7.0.1`
